{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.7.jar",
          "url": "injector-plugin-2.0.7.jar",
          "size": 125359,
          "sha512": "5dda65752cae921ea7c22bdad0caaad76961fa03b294ef165ccd2004c5967cb0a9014acf350fd78b85dc5eb321d1aa6cf9170d096ee9c6d76bb148ac3361687d",
          "sha256": "52fb8a286dd06bc95fda2d35108b10d1f595ff04b5b8c5cf19a67b4cb0b0bdbc",
          "sha1": "b1fa7503e2850d5f0d451f28f27cb3755e45f791",
          "md5": "6ad6fe29d100b7ff2234109e4da8f550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.7.jar",
          "url": "injector-plugin-2.0.7.jar",
          "size": 125359,
          "sha512": "5dda65752cae921ea7c22bdad0caaad76961fa03b294ef165ccd2004c5967cb0a9014acf350fd78b85dc5eb321d1aa6cf9170d096ee9c6d76bb148ac3361687d",
          "sha256": "52fb8a286dd06bc95fda2d35108b10d1f595ff04b5b8c5cf19a67b4cb0b0bdbc",
          "sha1": "b1fa7503e2850d5f0d451f28f27cb3755e45f791",
          "md5": "6ad6fe29d100b7ff2234109e4da8f550"
        }
      ]
    }
  ]
}
