{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.7.jar",
          "url": "injector-plugin-2.0.7.jar",
          "size": 127520,
          "sha512": "ab286888510149407d8faeedbe4c710ffe3a8dd3eca1a6020bbbbabd90aabc1834ec74c5a20c123dbd6c97eac905e5c6060b84a59810704e9885ea1dbbcd3679",
          "sha256": "4fdf9ed009678d06cd78480922c7a6c7105bea3de2a87999d4fb7ac847e6f99a",
          "sha1": "510154828e3e0b1063f96dbe83ac1c0371badc93",
          "md5": "be58f87e928dc1cd5e2ac536145ce30a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.7.jar",
          "url": "injector-plugin-2.0.7.jar",
          "size": 127520,
          "sha512": "ab286888510149407d8faeedbe4c710ffe3a8dd3eca1a6020bbbbabd90aabc1834ec74c5a20c123dbd6c97eac905e5c6060b84a59810704e9885ea1dbbcd3679",
          "sha256": "4fdf9ed009678d06cd78480922c7a6c7105bea3de2a87999d4fb7ac847e6f99a",
          "sha1": "510154828e3e0b1063f96dbe83ac1c0371badc93",
          "md5": "be58f87e928dc1cd5e2ac536145ce30a"
        }
      ]
    }
  ]
}
