{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "edab899259beaf25756c31dfbc17841838c8c7a8e67323e63600d1e57def8c947ed8b6920a6e9e3bb929cd148f4d729016346901bcca745efaf60da18cc66bef",
          "sha256": "1ff5c1679d98eadb89371a911340de06963695d3e0275c5c42bf1adcac6e3e9b",
          "sha1": "d19750013e5459166de3f4042a34215c44c807cb",
          "md5": "2f9fdcd5994e034daa49b33d8dc9bf16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "edab899259beaf25756c31dfbc17841838c8c7a8e67323e63600d1e57def8c947ed8b6920a6e9e3bb929cd148f4d729016346901bcca745efaf60da18cc66bef",
          "sha256": "1ff5c1679d98eadb89371a911340de06963695d3e0275c5c42bf1adcac6e3e9b",
          "sha1": "d19750013e5459166de3f4042a34215c44c807cb",
          "md5": "2f9fdcd5994e034daa49b33d8dc9bf16"
        }
      ]
    }
  ]
}
