{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "469af8a277881054eed109cf6841d1fa4c5dc7c1194179c610b23484cb4a525c403a36ec3b3d8ea7d45d4292749c7b975daf9c2f9e3ed8e5c31e8382b1d91de2",
          "sha256": "feb619647fdb935253f6e4fc8c531ed2669ff8d7250eda61b4821680e59cb716",
          "sha1": "d0ee831f1f3935bf193cab2515c45fa78c69c85e",
          "md5": "1fc718143bdffd7c22deb45e75c376cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "469af8a277881054eed109cf6841d1fa4c5dc7c1194179c610b23484cb4a525c403a36ec3b3d8ea7d45d4292749c7b975daf9c2f9e3ed8e5c31e8382b1d91de2",
          "sha256": "feb619647fdb935253f6e4fc8c531ed2669ff8d7250eda61b4821680e59cb716",
          "sha1": "d0ee831f1f3935bf193cab2515c45fa78c69c85e",
          "md5": "1fc718143bdffd7c22deb45e75c376cf"
        }
      ]
    }
  ]
}
