{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "dfabea782322f324cc492a21083f0a34b0ed07b567502ff1eafaf6a153919eec959f946202ac07c18452490f2e82017c3d9f123ccb45ec29c90ca69e0d53b0cc",
          "sha256": "5d2e0743b21e75c95e19adf082d182325ceeab8926fde17ad36a1b88cad1d349",
          "sha1": "4478ba95913d9f0ff93f1067bab71031226e07cd",
          "md5": "8880458efdd239898589d7f2f6502b11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "dfabea782322f324cc492a21083f0a34b0ed07b567502ff1eafaf6a153919eec959f946202ac07c18452490f2e82017c3d9f123ccb45ec29c90ca69e0d53b0cc",
          "sha256": "5d2e0743b21e75c95e19adf082d182325ceeab8926fde17ad36a1b88cad1d349",
          "sha1": "4478ba95913d9f0ff93f1067bab71031226e07cd",
          "md5": "8880458efdd239898589d7f2f6502b11"
        }
      ]
    }
  ]
}
