{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.17.jar",
          "url": "injector-plugin-2.0.17.jar",
          "size": 129979,
          "sha512": "25f4bb3364496f158b45801e8b1225b0c238129ee01568a79cdecae8cae9da21f93f738971bc08309e7dffcd645a5bbedcbce4cb3596f4dba9e2ed4b8e4396f9",
          "sha256": "715150d61308af250b128942d5e3b609da90c7f95a5e775b1b0f71840c92f4f0",
          "sha1": "7fa744e32a53c1b53d660da033cc4a9736d18cf7",
          "md5": "d22dc16b1278ae16b52a6ddd6f114b04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.20-EXPERIMENTAL"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.17.jar",
          "url": "injector-plugin-2.0.17.jar",
          "size": 129979,
          "sha512": "25f4bb3364496f158b45801e8b1225b0c238129ee01568a79cdecae8cae9da21f93f738971bc08309e7dffcd645a5bbedcbce4cb3596f4dba9e2ed4b8e4396f9",
          "sha256": "715150d61308af250b128942d5e3b609da90c7f95a5e775b1b0f71840c92f4f0",
          "sha1": "7fa744e32a53c1b53d660da033cc4a9736d18cf7",
          "md5": "d22dc16b1278ae16b52a6ddd6f114b04"
        }
      ]
    }
  ]
}
