{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.27.jar",
          "url": "injector-plugin-2.0.27.jar",
          "size": 137578,
          "sha512": "444b80ca9ad337c972eae4afd723bf1f35c410926deb0a4fd460a4fc30af1bf470de86dd1d83871142c9536cd121b3b0622c22dcc1c887d451eb502e2c1b42f7",
          "sha256": "55879f4ca9760c83cddb6ff7a05eeb78ed2320747c81ccc9a78784b787db2a2d",
          "sha1": "297c622c3c22c9dc43840e729e4e8e3b87ef1949",
          "md5": "91a7e1b3025a28ad55be67f50b03053e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.27.jar",
          "url": "injector-plugin-2.0.27.jar",
          "size": 137578,
          "sha512": "444b80ca9ad337c972eae4afd723bf1f35c410926deb0a4fd460a4fc30af1bf470de86dd1d83871142c9536cd121b3b0622c22dcc1c887d451eb502e2c1b42f7",
          "sha256": "55879f4ca9760c83cddb6ff7a05eeb78ed2320747c81ccc9a78784b787db2a2d",
          "sha1": "297c622c3c22c9dc43840e729e4e8e3b87ef1949",
          "md5": "91a7e1b3025a28ad55be67f50b03053e"
        }
      ]
    }
  ]
}
