{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "4e43bab187b62d5165f787cb477e878b856b05412a7eae2e349090ea1591fc7b6b0a91b798d42ffe7976be1d7437f859578adb09fa085ca42aa61f5cac2c5f60",
          "sha256": "18cb8df23dfc20cf8134d4623e30082439ad7d890ccaa3ad3bfea753cafc9cc7",
          "sha1": "e891a1ac099f152fc7dddd47db68ca7b045cbea5",
          "md5": "44470f3644b5ebe82c0b61c29ebc3093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "4e43bab187b62d5165f787cb477e878b856b05412a7eae2e349090ea1591fc7b6b0a91b798d42ffe7976be1d7437f859578adb09fa085ca42aa61f5cac2c5f60",
          "sha256": "18cb8df23dfc20cf8134d4623e30082439ad7d890ccaa3ad3bfea753cafc9cc7",
          "sha1": "e891a1ac099f152fc7dddd47db68ca7b045cbea5",
          "md5": "44470f3644b5ebe82c0b61c29ebc3093"
        }
      ]
    }
  ]
}
