{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "10c55cad518d678f6636881c7e70c9afdcf0e0451a1da34d0558712b0b98511033f973702e4e564a4e4fd2ec60412da895ecfcc3e43031a3be08219f1efed7f6",
          "sha256": "c58036f3d17908fb1b5de8aab3c24a858e5c83eff3cc15db800d70ae08d922b1",
          "sha1": "ff550ff015963a895a4e18ab70c4d8fcba868359",
          "md5": "90f7702cf208894169f01c4acc67d5d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "10c55cad518d678f6636881c7e70c9afdcf0e0451a1da34d0558712b0b98511033f973702e4e564a4e4fd2ec60412da895ecfcc3e43031a3be08219f1efed7f6",
          "sha256": "c58036f3d17908fb1b5de8aab3c24a858e5c83eff3cc15db800d70ae08d922b1",
          "sha1": "ff550ff015963a895a4e18ab70c4d8fcba868359",
          "md5": "90f7702cf208894169f01c4acc67d5d5"
        }
      ]
    }
  ]
}
