{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "58969a6e767d31ee5e61e398f6c01c13277c667aa86101677594a2909ee0dcca7ac8ff919ee80d7d9b8ad4610be3277b3bce73f735af78be5097966de1cb50f8",
          "sha256": "65e4c8fa49e377dedf51c6adf204a6b337e31081ab91098b0c2eaf799852715e",
          "sha1": "0e87206ed536c9bcbe8094f98279f458f7361c83",
          "md5": "ef35e5c424f5ef2f00acce5fc3a561d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "58969a6e767d31ee5e61e398f6c01c13277c667aa86101677594a2909ee0dcca7ac8ff919ee80d7d9b8ad4610be3277b3bce73f735af78be5097966de1cb50f8",
          "sha256": "65e4c8fa49e377dedf51c6adf204a6b337e31081ab91098b0c2eaf799852715e",
          "sha1": "0e87206ed536c9bcbe8094f98279f458f7361c83",
          "md5": "ef35e5c424f5ef2f00acce5fc3a561d9"
        }
      ]
    }
  ]
}
