{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.6.jar",
          "url": "injector-plugin-2.0.5.6.jar",
          "size": 122643,
          "sha512": "46b44ec1330c6635473116795088077ee7144b15c506a86d66c4dad45088f698aaef968f02e716bee6acb02743689c0671d4f20d2e3b7d7d93c86e8b897030f4",
          "sha256": "742f99ce8a4467f953a67a65780654654ba87896188cdbcc3771d2853e171518",
          "sha1": "64bd16df2c739a568f8d7f4fa431a348b91d30e2",
          "md5": "fd9fa1afdb99f9b2fe0e612f5fa71f83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.6.jar",
          "url": "injector-plugin-2.0.5.6.jar",
          "size": 122643,
          "sha512": "46b44ec1330c6635473116795088077ee7144b15c506a86d66c4dad45088f698aaef968f02e716bee6acb02743689c0671d4f20d2e3b7d7d93c86e8b897030f4",
          "sha256": "742f99ce8a4467f953a67a65780654654ba87896188cdbcc3771d2853e171518",
          "sha1": "64bd16df2c739a568f8d7f4fa431a348b91d30e2",
          "md5": "fd9fa1afdb99f9b2fe0e612f5fa71f83"
        }
      ]
    }
  ]
}
