{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.6.jar",
          "url": "injector-plugin-2.0.5.6.jar",
          "size": 127520,
          "sha512": "21693b9e9def11fc334224e0046e28e3d9948f534a241c1021e4473727b0d630217d8abd9ca24f3b6b57a1fbb870030c7021260707fd1293bb69a71697a41e65",
          "sha256": "77cf4a95a022cc7f70d9a12152bc3e7dab6f249dbcc278eb7263114f79c1706c",
          "sha1": "fe9e49e51c17ac00e561e0c6084269e1f733b441",
          "md5": "b1946b754b0a5a5c67248aed05c18213"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.6.jar",
          "url": "injector-plugin-2.0.5.6.jar",
          "size": 127520,
          "sha512": "21693b9e9def11fc334224e0046e28e3d9948f534a241c1021e4473727b0d630217d8abd9ca24f3b6b57a1fbb870030c7021260707fd1293bb69a71697a41e65",
          "sha256": "77cf4a95a022cc7f70d9a12152bc3e7dab6f249dbcc278eb7263114f79c1706c",
          "sha1": "fe9e49e51c17ac00e561e0c6084269e1f733b441",
          "md5": "b1946b754b0a5a5c67248aed05c18213"
        }
      ]
    }
  ]
}
