{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "69963170c35f498d5bf64a4448ce8a516b2428681e8f97e4701bc0cbc42639189fe9c3dff8267d41d5d1bfab734a29310b0dc8100d3fd2f1609e4b2c27917c91",
          "sha256": "b153248e3d6e7293336bb46929fdb0f138f3a74fe50fa2cef1fd85240d869545",
          "sha1": "0aaeabeaea4ae8da3861e33ff4b48157ed81301c",
          "md5": "76feb2e061e0b2de7b3f821abbcc49a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "69963170c35f498d5bf64a4448ce8a516b2428681e8f97e4701bc0cbc42639189fe9c3dff8267d41d5d1bfab734a29310b0dc8100d3fd2f1609e4b2c27917c91",
          "sha256": "b153248e3d6e7293336bb46929fdb0f138f3a74fe50fa2cef1fd85240d869545",
          "sha1": "0aaeabeaea4ae8da3861e33ff4b48157ed81301c",
          "md5": "76feb2e061e0b2de7b3f821abbcc49a7"
        }
      ]
    }
  ]
}
