{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "9ec1d80e606cbebc2ab5ae915046dddaf1f3aa9d8b09cb05c2a4a733ffae6d58fce08be46021555a9a799a0cfd057ea82f246e9ef69594432c52ff0c3122d8c8",
          "sha256": "50036b1bcfdb1dc746feb00519fb3cf9ca06ebcfdd4877f8619555c676a6bd81",
          "sha1": "5c195493d139e340b8e1a3d188ec6f236416fa71",
          "md5": "ed4bf6df50b6a6d9a5afcfe8f8cb2567"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "9ec1d80e606cbebc2ab5ae915046dddaf1f3aa9d8b09cb05c2a4a733ffae6d58fce08be46021555a9a799a0cfd057ea82f246e9ef69594432c52ff0c3122d8c8",
          "sha256": "50036b1bcfdb1dc746feb00519fb3cf9ca06ebcfdd4877f8619555c676a6bd81",
          "sha1": "5c195493d139e340b8e1a3d188ec6f236416fa71",
          "md5": "ed4bf6df50b6a6d9a5afcfe8f8cb2567"
        }
      ]
    }
  ]
}
