{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "1e950d1efb7280c4bdd43c08b9eee454fca3310d2902227e416abb5bed8dabd5ba835366e692e24a1641f9ff3b18639a748c049051206d5d35a401bba15a5067",
          "sha256": "bf3a35b49131d76cdfd742aa088a60987f0e713a4918270e8814b8277f3b71cb",
          "sha1": "c5a1345c4fdce4adcd3a865586fe8f61366e6d47",
          "md5": "3438702e6f6e598c5a41534da7917b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "1e950d1efb7280c4bdd43c08b9eee454fca3310d2902227e416abb5bed8dabd5ba835366e692e24a1641f9ff3b18639a748c049051206d5d35a401bba15a5067",
          "sha256": "bf3a35b49131d76cdfd742aa088a60987f0e713a4918270e8814b8277f3b71cb",
          "sha1": "c5a1345c4fdce4adcd3a865586fe8f61366e6d47",
          "md5": "3438702e6f6e598c5a41534da7917b18"
        }
      ]
    }
  ]
}
