{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.11-SNAPSHOT.jar",
          "url": "http-api-1.0.11-SNAPSHOT.jar",
          "size": 95113,
          "sha512": "e7edd85d090a8be8de1d32bc7f3dd4120917e72613bb61cbfa561eb7650ee0f0fba11d4a0cae1dd349fcc0c8642f585fd785a3125fa3377852e39cd0c861abdd",
          "sha256": "d1dc1ee2833076f4fabe3e9e4b05e5a49431a4494473f71d80103ab07d9e886e",
          "sha1": "984321c8e1f55ed9cc1ee4825f6cb1e356248b24",
          "md5": "1dec8006ea64f5083376005a2e3963fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.11-SNAPSHOT.jar",
          "url": "http-api-1.0.11-SNAPSHOT.jar",
          "size": 95113,
          "sha512": "e7edd85d090a8be8de1d32bc7f3dd4120917e72613bb61cbfa561eb7650ee0f0fba11d4a0cae1dd349fcc0c8642f585fd785a3125fa3377852e39cd0c861abdd",
          "sha256": "d1dc1ee2833076f4fabe3e9e4b05e5a49431a4494473f71d80103ab07d9e886e",
          "sha1": "984321c8e1f55ed9cc1ee4825f6cb1e356248b24",
          "md5": "1dec8006ea64f5083376005a2e3963fd"
        }
      ]
    }
  ]
}
