{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.24.jar",
          "url": "injector-plugin-2.0.24.jar",
          "size": 135728,
          "sha512": "4f21d023fe4db663c99b1eebb51cf64913b6c0d17b1d48e95e08c5bd1bc4c9d4dcfefa42fb4d8f80be11082b82ca3570b620fa6a255c065fbc2d5657f7bdfba0",
          "sha256": "2c3574aa5154d391a383232432968c140ea997e54482d9749b7f013ba6aeb03c",
          "sha1": "52ba8bfee261e2c333b858c93c2c7c2e656d2aaf",
          "md5": "9b524404afcc7e8349580bad2835c47b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.24.jar",
          "url": "injector-plugin-2.0.24.jar",
          "size": 135728,
          "sha512": "4f21d023fe4db663c99b1eebb51cf64913b6c0d17b1d48e95e08c5bd1bc4c9d4dcfefa42fb4d8f80be11082b82ca3570b620fa6a255c065fbc2d5657f7bdfba0",
          "sha256": "2c3574aa5154d391a383232432968c140ea997e54482d9749b7f013ba6aeb03c",
          "sha1": "52ba8bfee261e2c333b858c93c2c7c2e656d2aaf",
          "md5": "9b524404afcc7e8349580bad2835c47b"
        }
      ]
    }
  ]
}
