{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "script-assembler-plugin",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.5.jar",
          "url": "script-assembler-plugin-1.0.5.jar",
          "size": 8723,
          "sha512": "d6e36d82998e65d173ed6c3435976022d91b4fb60b56948d32653e366ab67016c93ba0e1aa337edeb167ee18c8bcc6d8265fe305392d56803047b361a9503f92",
          "sha256": "251868043bfc562db816969df6ffb40a02fa8c4767e28120e395ea52242c808c",
          "sha1": "9c360f047a21406a1ed9cdbd9111e15db1a36d24",
          "md5": "88a54db720be016deb49439b8b850650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "net.runelite",
          "module": "cache",
          "version": {
            "requires": "1.11.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.5.jar",
          "url": "script-assembler-plugin-1.0.5.jar",
          "size": 8723,
          "sha512": "d6e36d82998e65d173ed6c3435976022d91b4fb60b56948d32653e366ab67016c93ba0e1aa337edeb167ee18c8bcc6d8265fe305392d56803047b361a9503f92",
          "sha256": "251868043bfc562db816969df6ffb40a02fa8c4767e28120e395ea52242c808c",
          "sha1": "9c360f047a21406a1ed9cdbd9111e15db1a36d24",
          "md5": "88a54db720be016deb49439b8b850650"
        }
      ]
    }
  ]
}
