{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.21.jar",
          "url": "injector-plugin-2.0.21.jar",
          "size": 135760,
          "sha512": "b818b1bee00d3f6f77f70b678e5750017811aebaba6b73b0e1fe6bd906def648aa22cf4e52121eecb17f2e977bb33dd7a50606bd4be95a982cfa665527ad8f12",
          "sha256": "c210643a3a8029a6fa69f12835da733d49ffd1b940009dcb6355aeabe035380d",
          "sha1": "0739eae2fa6d4dca74f0e8999cf8d7823b73cbf9",
          "md5": "6cf63da7bb03b1c533d0e9014e852b6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.21.jar",
          "url": "injector-plugin-2.0.21.jar",
          "size": 135760,
          "sha512": "b818b1bee00d3f6f77f70b678e5750017811aebaba6b73b0e1fe6bd906def648aa22cf4e52121eecb17f2e977bb33dd7a50606bd4be95a982cfa665527ad8f12",
          "sha256": "c210643a3a8029a6fa69f12835da733d49ffd1b940009dcb6355aeabe035380d",
          "sha1": "0739eae2fa6d4dca74f0e8999cf8d7823b73cbf9",
          "md5": "6cf63da7bb03b1c533d0e9014e852b6b"
        }
      ]
    }
  ]
}
