{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.19.jar",
          "url": "injector-plugin-2.0.19.jar",
          "size": 130892,
          "sha512": "b664aa4edbb3fb4cfda549364130e12a13902f110e11fb49c03664e013fa56324b474de14a4252a3fcd3fd7fca28cc4b1c9f6f7b4fcb3479857b9569514caf66",
          "sha256": "f6347d8e3017a97a88014e3d3cc074d5495fdefe88834548f5927cdda16c3443",
          "sha1": "3d93c2c4ca009d7933970d450d7ce4329872e1ba",
          "md5": "4d785ebe75587dc4fae44e045f9c5348"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.20-EXPERIMENTAL"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.19.jar",
          "url": "injector-plugin-2.0.19.jar",
          "size": 130892,
          "sha512": "b664aa4edbb3fb4cfda549364130e12a13902f110e11fb49c03664e013fa56324b474de14a4252a3fcd3fd7fca28cc4b1c9f6f7b4fcb3479857b9569514caf66",
          "sha256": "f6347d8e3017a97a88014e3d3cc074d5495fdefe88834548f5927cdda16c3443",
          "sha1": "3d93c2c4ca009d7933970d450d7ce4329872e1ba",
          "md5": "4d785ebe75587dc4fae44e045f9c5348"
        }
      ]
    }
  ]
}
