{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.18.jar",
          "url": "injector-plugin-2.0.18.jar",
          "size": 129979,
          "sha512": "ba8791120c73ff0dcd92f4b8c7baf63128315e21b42bd1151b610f5db11cf13df206ac63eb2771038ab72450fd3d0de66087ceaeea14a7a7b1d55eabc0a94150",
          "sha256": "bef9a14325340faf2455d3f40358b0177b7364d43e557707172cec1f5582cfa7",
          "sha1": "1d08f4d319d35c530fd521c7ffb845f45867d21e",
          "md5": "c124a2ab576e8858809531dacc8bc32d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.18.jar",
          "url": "injector-plugin-2.0.18.jar",
          "size": 129979,
          "sha512": "ba8791120c73ff0dcd92f4b8c7baf63128315e21b42bd1151b610f5db11cf13df206ac63eb2771038ab72450fd3d0de66087ceaeea14a7a7b1d55eabc0a94150",
          "sha256": "bef9a14325340faf2455d3f40358b0177b7364d43e557707172cec1f5582cfa7",
          "sha1": "1d08f4d319d35c530fd521c7ffb845f45867d21e",
          "md5": "c124a2ab576e8858809531dacc8bc32d"
        }
      ]
    }
  ]
}
