{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.14.jar",
          "url": "injector-plugin-2.0.14.jar",
          "size": 130020,
          "sha512": "1de738a01c9b39220945de7850312df38a21e9ea77068dcddd7c114fb6f1903ce30931a3abefa8fc6ed1513fa83bbedd6139927449fcc185b526549e4c8e03e0",
          "sha256": "79830104241bd6022966c3bf9b0b6a7091fd88ac41f358c2ee73ba6697d0ebe5",
          "sha1": "b9b02fbc5eb10f9344117363b8aa06fa7aef2366",
          "md5": "80ff6424002b87bf95f6319d6c5f8757"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.14.jar",
          "url": "injector-plugin-2.0.14.jar",
          "size": 130020,
          "sha512": "1de738a01c9b39220945de7850312df38a21e9ea77068dcddd7c114fb6f1903ce30931a3abefa8fc6ed1513fa83bbedd6139927449fcc185b526549e4c8e03e0",
          "sha256": "79830104241bd6022966c3bf9b0b6a7091fd88ac41f358c2ee73ba6697d0ebe5",
          "sha1": "b9b02fbc5eb10f9344117363b8aa06fa7aef2366",
          "md5": "80ff6424002b87bf95f6319d6c5f8757"
        }
      ]
    }
  ]
}
