{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.14.jar",
          "url": "injector-plugin-2.0.14.jar",
          "size": 127750,
          "sha512": "a4c04e0bf0086de0f3dcd7624c62615ebbbe0b688fbbf13c13cd760be6f161a455335124f07ace0d602f81f8953661d72d2b2219d5d4571ea1f4f866273e72b2",
          "sha256": "ac779aef65d916bcc40ac6e4979127b5b6ddbd4346b50b9dac690a3d0c0f6c92",
          "sha1": "225c89ca8da27ace385af995728b9ace2f9f6bb6",
          "md5": "a2c46b31dbf06b727f6dfe836aa3cd52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.14.jar",
          "url": "injector-plugin-2.0.14.jar",
          "size": 127750,
          "sha512": "a4c04e0bf0086de0f3dcd7624c62615ebbbe0b688fbbf13c13cd760be6f161a455335124f07ace0d602f81f8953661d72d2b2219d5d4571ea1f4f866273e72b2",
          "sha256": "ac779aef65d916bcc40ac6e4979127b5b6ddbd4346b50b9dac690a3d0c0f6c92",
          "sha1": "225c89ca8da27ace385af995728b9ace2f9f6bb6",
          "md5": "a2c46b31dbf06b727f6dfe836aa3cd52"
        }
      ]
    }
  ]
}
