{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "658f6b77073212da8a8a4a6f121cb7d8f61384054cb72dd55ff40352fbb120c6ad0690080828524f57f9448a969c716d4af2356599da42a335d3625ad4c2de14",
          "sha256": "2a4ddacfb26b09f5df9477bc1847493b1b5f92ba2eef4b09c72a0c9a691157a4",
          "sha1": "df6a2085562a25e1a73c45be8e8936f10afa0b86",
          "md5": "d54094c7888a06b087bb1c22f4b86687"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "658f6b77073212da8a8a4a6f121cb7d8f61384054cb72dd55ff40352fbb120c6ad0690080828524f57f9448a969c716d4af2356599da42a335d3625ad4c2de14",
          "sha256": "2a4ddacfb26b09f5df9477bc1847493b1b5f92ba2eef4b09c72a0c9a691157a4",
          "sha1": "df6a2085562a25e1a73c45be8e8936f10afa0b86",
          "md5": "d54094c7888a06b087bb1c22f4b86687"
        }
      ]
    }
  ]
}
