{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "619c7f4a5d20d90ac9d48bc08bcb21ee1abe8d29578ac743baaa4c20f117fc9b971de317dafc75a5dfbfaafcb78db6c78837a4670d61e615ed3b9252bbd84f38",
          "sha256": "e842b96961b9c8a254cedf1ece53d650569f7ca8e34328209bcf12bd0e3db8af",
          "sha1": "da29107fc27a373ec4362d11eaa1d44029fe0771",
          "md5": "c0b49f79c6de062812daa410c7d6ae62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "619c7f4a5d20d90ac9d48bc08bcb21ee1abe8d29578ac743baaa4c20f117fc9b971de317dafc75a5dfbfaafcb78db6c78837a4670d61e615ed3b9252bbd84f38",
          "sha256": "e842b96961b9c8a254cedf1ece53d650569f7ca8e34328209bcf12bd0e3db8af",
          "sha1": "da29107fc27a373ec4362d11eaa1d44029fe0771",
          "md5": "c0b49f79c6de062812daa410c7d6ae62"
        }
      ]
    }
  ]
}
