{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "586600c493153e1336513770a5d1032675fc00a0cfbd340308d6c85a1ce8937b25ea7fb52e5e650b88a848d60f8a03fcb17de56b8072361e118eabaa401f9490",
          "sha256": "79f097c29e17eef6c640538a3df2e3dbca3b34699063478b14c6dd4977b8daae",
          "sha1": "c429ec53eadfb6d6202f4b747d80a21e091b90ad",
          "md5": "760b0a303d3010496be0eda48024e40d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "586600c493153e1336513770a5d1032675fc00a0cfbd340308d6c85a1ce8937b25ea7fb52e5e650b88a848d60f8a03fcb17de56b8072361e118eabaa401f9490",
          "sha256": "79f097c29e17eef6c640538a3df2e3dbca3b34699063478b14c6dd4977b8daae",
          "sha1": "c429ec53eadfb6d6202f4b747d80a21e091b90ad",
          "md5": "760b0a303d3010496be0eda48024e40d"
        }
      ]
    }
  ]
}
