{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.jar",
          "url": "injector-plugin-2.0.5.jar",
          "size": 121136,
          "sha512": "c775777141dd1b14695869b361397fd2eb7eacecae12900164a9af6685fc8a7a91f41fb0fc2f862791c4da410e09590bb127754f7eba74c760863555ffdc7881",
          "sha256": "93ea61e7d6d2b80965ea46cd23e63242dd0dfaf5f0a5e06c9dcfe7accac4ff56",
          "sha1": "0f96e953ed3385550da0fed6d5c5dca3bab6c16c",
          "md5": "f08d59f78c480a53148b78849307baae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.5.jar",
          "url": "injector-plugin-2.0.5.jar",
          "size": 121136,
          "sha512": "c775777141dd1b14695869b361397fd2eb7eacecae12900164a9af6685fc8a7a91f41fb0fc2f862791c4da410e09590bb127754f7eba74c760863555ffdc7881",
          "sha256": "93ea61e7d6d2b80965ea46cd23e63242dd0dfaf5f0a5e06c9dcfe7accac4ff56",
          "sha1": "0f96e953ed3385550da0fed6d5c5dca3bab6c16c",
          "md5": "f08d59f78c480a53148b78849307baae"
        }
      ]
    }
  ]
}
