{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "009822c523b8faf9e2df2891260a1321d01740cc42a5dff8d2c1aee8a2478f39c5bafb706caac191dc9871ca3aac28ace1b52f46355b16038a372c4640d22153",
          "sha256": "b19c75bc1cf7e8a7d9f87e1e3bb60225ef29b526ea509f304eff05bff80dc7d2",
          "sha1": "05f515077d20d3639493807758172e4a2be7fe3c",
          "md5": "1e240b10abd6209e5e51911ac72604e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "009822c523b8faf9e2df2891260a1321d01740cc42a5dff8d2c1aee8a2478f39c5bafb706caac191dc9871ca3aac28ace1b52f46355b16038a372c4640d22153",
          "sha256": "b19c75bc1cf7e8a7d9f87e1e3bb60225ef29b526ea509f304eff05bff80dc7d2",
          "sha1": "05f515077d20d3639493807758172e4a2be7fe3c",
          "md5": "1e240b10abd6209e5e51911ac72604e1"
        }
      ]
    }
  ]
}
