{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "cacc4c376cf79fbbc1b72608804d188ef7619ab847c16b4d796f75dafdf5ebd9fe8d43322c866403d6b49bd16ff8114c9aec7665739a81bd314c62db4f585416",
          "sha256": "f0cdbbef77286a9e4e55f661848bb1d2a790fdff43ff66e4f0a4a03ae3a25782",
          "sha1": "5935eac4731d97e850728b7d08c8b40ec5b22527",
          "md5": "c7596526fd3e1782df55bbe38a70b3d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "cacc4c376cf79fbbc1b72608804d188ef7619ab847c16b4d796f75dafdf5ebd9fe8d43322c866403d6b49bd16ff8114c9aec7665739a81bd314c62db4f585416",
          "sha256": "f0cdbbef77286a9e4e55f661848bb1d2a790fdff43ff66e4f0a4a03ae3a25782",
          "sha1": "5935eac4731d97e850728b7d08c8b40ec5b22527",
          "md5": "c7596526fd3e1782df55bbe38a70b3d7"
        }
      ]
    }
  ]
}
