{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "4a4835302bba208884b1d857478aaa2d1b1e082b207dd14a615080b70a07fd39a793c0fa286864f6ad799c5ba5f75f9eacaf25a67c1f7c4acf735ed6ad5ad6a2",
          "sha256": "5c55d3f40bacaa9ad7db69ecacca2f2ee2fc69ee316a887277432b95f7a7f692",
          "sha1": "150924948dead2e0b0bd188f7f8f4e7e2c52fd3e",
          "md5": "60f99d739835efeb7fb8c9eb33d292eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "4a4835302bba208884b1d857478aaa2d1b1e082b207dd14a615080b70a07fd39a793c0fa286864f6ad799c5ba5f75f9eacaf25a67c1f7c4acf735ed6ad5ad6a2",
          "sha256": "5c55d3f40bacaa9ad7db69ecacca2f2ee2fc69ee316a887277432b95f7a7f692",
          "sha1": "150924948dead2e0b0bd188f7f8f4e7e2c52fd3e",
          "md5": "60f99d739835efeb7fb8c9eb33d292eb"
        }
      ]
    }
  ]
}
