{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.25.jar",
          "url": "injector-plugin-2.0.25.jar",
          "size": 135801,
          "sha512": "9e4c68f74eab0acf6113e5a1fb49b2ab70ea555a9090f3e77d472af01832235f81356a301dc3ef6b69afddefbc6753ea5102037d95803b8e62896681850c3011",
          "sha256": "0b1b3469ec47ee65e2745b5602133f12b2fbc9c9381498254f1c83545bd9ead2",
          "sha1": "b9faf763f4394c45f932229d4b022b8f483fb121",
          "md5": "2133259a0650c000209fb35695ed1379"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.25.jar",
          "url": "injector-plugin-2.0.25.jar",
          "size": 135801,
          "sha512": "9e4c68f74eab0acf6113e5a1fb49b2ab70ea555a9090f3e77d472af01832235f81356a301dc3ef6b69afddefbc6753ea5102037d95803b8e62896681850c3011",
          "sha256": "0b1b3469ec47ee65e2745b5602133f12b2fbc9c9381498254f1c83545bd9ead2",
          "sha1": "b9faf763f4394c45f932229d4b022b8f483fb121",
          "md5": "2133259a0650c000209fb35695ed1379"
        }
      ]
    }
  ]
}
