{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.8.jar",
          "url": "injector-plugin-2.0.8.jar",
          "size": 128190,
          "sha512": "b09b4744197ce6e8548c90bd46c6676805580fa9571eb2de482176eee087ba5ae657da959c0df62327c1e6f97a40dad04681284baf60dd421896f0284545a17e",
          "sha256": "d22deb2132d8790276c89866daed9b0ce41ae8ed4e24b6ba5a1f5e57e254376d",
          "sha1": "6997b6264611a7d404ef46bb56197167b334f0c5",
          "md5": "9fe52c44083a8b06109ff124929e875a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.8.jar",
          "url": "injector-plugin-2.0.8.jar",
          "size": 128190,
          "sha512": "b09b4744197ce6e8548c90bd46c6676805580fa9571eb2de482176eee087ba5ae657da959c0df62327c1e6f97a40dad04681284baf60dd421896f0284545a17e",
          "sha256": "d22deb2132d8790276c89866daed9b0ce41ae8ed4e24b6ba5a1f5e57e254376d",
          "sha1": "6997b6264611a7d404ef46bb56197167b334f0c5",
          "md5": "9fe52c44083a8b06109ff124929e875a"
        }
      ]
    }
  ]
}
