{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.8.jar",
          "url": "injector-plugin-2.0.8.jar",
          "size": 127520,
          "sha512": "939e9122a8a75dddc9400bf660f44c9d436ee12daf1034c4f72394a9b65ff32dd1fc9340dcafbece30f6c9c00bfe1e9cba18f4495053939498e7d952654b829e",
          "sha256": "e5fc5c13d4ae3327396c25391d66608da82f219778765d3608104d1980ef9f7a",
          "sha1": "6ac31f70488b6220f61a79cfd868d6cec4ec2140",
          "md5": "7471650c2f8899e4384266bf85b9daf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.8.jar",
          "url": "injector-plugin-2.0.8.jar",
          "size": 127520,
          "sha512": "939e9122a8a75dddc9400bf660f44c9d436ee12daf1034c4f72394a9b65ff32dd1fc9340dcafbece30f6c9c00bfe1e9cba18f4495053939498e7d952654b829e",
          "sha256": "e5fc5c13d4ae3327396c25391d66608da82f219778765d3608104d1980ef9f7a",
          "sha1": "6ac31f70488b6220f61a79cfd868d6cec4ec2140",
          "md5": "7471650c2f8899e4384266bf85b9daf9"
        }
      ]
    }
  ]
}
