{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "interface-parser-plugin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "interface-parser-plugin-1.0.3.jar",
          "url": "interface-parser-plugin-1.0.3.jar",
          "size": 7623,
          "sha512": "762ee606b2002daec29a97d37c9bfbfc90c5ceeb51e597af5f50d9a30015dab85af6931a18d0b8a439f319daf7e3ba5f35a5b1c5634ad515e94d5e3668d724d5",
          "sha256": "2e19ea4776a1fdea73dab394a142174561673f477ff07849166fe5c571eaa8c7",
          "sha1": "5ab4e38a7d3e6006918c88221598ca5f7701f327",
          "md5": "59e0253591f4901b9a4648d459f52254"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "net.sourceforge.pmd",
          "module": "pmd-core",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "net.sourceforge.pmd",
          "module": "pmd-java",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "interface-parser-plugin-1.0.3.jar",
          "url": "interface-parser-plugin-1.0.3.jar",
          "size": 7623,
          "sha512": "762ee606b2002daec29a97d37c9bfbfc90c5ceeb51e597af5f50d9a30015dab85af6931a18d0b8a439f319daf7e3ba5f35a5b1c5634ad515e94d5e3668d724d5",
          "sha256": "2e19ea4776a1fdea73dab394a142174561673f477ff07849166fe5c571eaa8c7",
          "sha1": "5ab4e38a7d3e6006918c88221598ca5f7701f327",
          "md5": "59e0253591f4901b9a4648d459f52254"
        }
      ]
    }
  ]
}
