{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "5c6476382502f45590e83d65762960df4d2fa2d37699ebd3a017884cc27468443c8d5c938c38aee70d085d348f9cb032284061765b9f8e9575b736e23d7deafc",
          "sha256": "75daa6ddb6d2c88572b47e795ecdd96e2ee7d4f896416e4847d46fdc10b741af",
          "sha1": "aac2a60d2af7937a6c1878c08a47d11ad0d206fe",
          "md5": "e1860c7f3d3617a3296ebc6911afdd8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "5c6476382502f45590e83d65762960df4d2fa2d37699ebd3a017884cc27468443c8d5c938c38aee70d085d348f9cb032284061765b9f8e9575b736e23d7deafc",
          "sha256": "75daa6ddb6d2c88572b47e795ecdd96e2ee7d4f896416e4847d46fdc10b741af",
          "sha1": "aac2a60d2af7937a6c1878c08a47d11ad0d206fe",
          "md5": "e1860c7f3d3617a3296ebc6911afdd8f"
        }
      ]
    }
  ]
}
