{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "59219767fe7379309e66073e379d91ac3358a38cbaf8651e85cb5c67b9e266cfacf2b42fb66d3fc79d7a4079203eaca6fd5763af015637e37e6e76cc0515d980",
          "sha256": "812650a7ce0c541007fcbd861434a4528c794e6668b14992937294e8c41eee97",
          "sha1": "9d8ef9b63f0f2835ab8c2682f2ac529c3fc101f6",
          "md5": "60baa7a6c139bf06b9e862629f835b1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "59219767fe7379309e66073e379d91ac3358a38cbaf8651e85cb5c67b9e266cfacf2b42fb66d3fc79d7a4079203eaca6fd5763af015637e37e6e76cc0515d980",
          "sha256": "812650a7ce0c541007fcbd861434a4528c794e6668b14992937294e8c41eee97",
          "sha1": "9d8ef9b63f0f2835ab8c2682f2ac529c3fc101f6",
          "md5": "60baa7a6c139bf06b9e862629f835b1a"
        }
      ]
    }
  ]
}
