{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "18aa7fa40de83fe058e30d62e3fb13b82fc285084e7411727f2e41d0eaca75d1142963cf9b4b4e8a1ec04925aa454371ea735a58658c25101f04be05dce150b0",
          "sha256": "87f053de73a81f6363b35db6eb31ab707219aaa8f4a325cffa50f6a6a6295ec0",
          "sha1": "522d5c9666cf12f2eb6a165f75aacd0375fd8785",
          "md5": "ad2ab6f1f801b2669c68630043bf8bbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "18aa7fa40de83fe058e30d62e3fb13b82fc285084e7411727f2e41d0eaca75d1142963cf9b4b4e8a1ec04925aa454371ea735a58658c25101f04be05dce150b0",
          "sha256": "87f053de73a81f6363b35db6eb31ab707219aaa8f4a325cffa50f6a6a6295ec0",
          "sha1": "522d5c9666cf12f2eb6a165f75aacd0375fd8785",
          "md5": "ad2ab6f1f801b2669c68630043bf8bbf"
        }
      ]
    }
  ]
}
