{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "6c02030ca071ecc5290d26a506eebf743a0633715974f5b5dc3b4c096fd4d69c6fc7f363592debdbe4404d1003d6e1e807ffe2d2c82ce47d3ecf4f990267745f",
          "sha256": "c50bd1ca182f0b6079437ee6f8d33f2bf3e91d597f49af77065ffc7f7e677ade",
          "sha1": "2cea9d37fb2aae6acf3db88f792a74b1f0576904",
          "md5": "78f30dc388bf7c2d6e4f10a0ee73506e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "6c02030ca071ecc5290d26a506eebf743a0633715974f5b5dc3b4c096fd4d69c6fc7f363592debdbe4404d1003d6e1e807ffe2d2c82ce47d3ecf4f990267745f",
          "sha256": "c50bd1ca182f0b6079437ee6f8d33f2bf3e91d597f49af77065ffc7f7e677ade",
          "sha1": "2cea9d37fb2aae6acf3db88f792a74b1f0576904",
          "md5": "78f30dc388bf7c2d6e4f10a0ee73506e"
        }
      ]
    }
  ]
}
