{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "9cb5c51b77de2509fc59c6ce15ae3f1da99c164bb9a857035faf05377267686fe85507aef6359dcc8dd9a3a59bb5acd766b0d4e9ef3e9e68c80b5388945506b3",
          "sha256": "3bb5622be47c15b2071073e4bb9ba9abd299a1e41071453e28a4651a9d0e3426",
          "sha1": "ae7f0f6cc53ec0b98e0711587497143e58d89310",
          "md5": "a7179036b54072802871311d295dd4a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "9cb5c51b77de2509fc59c6ce15ae3f1da99c164bb9a857035faf05377267686fe85507aef6359dcc8dd9a3a59bb5acd766b0d4e9ef3e9e68c80b5388945506b3",
          "sha256": "3bb5622be47c15b2071073e4bb9ba9abd299a1e41071453e28a4651a9d0e3426",
          "sha1": "ae7f0f6cc53ec0b98e0711587497143e58d89310",
          "md5": "a7179036b54072802871311d295dd4a4"
        }
      ]
    }
  ]
}
