{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "2764266f0e1a05a2bfea3b54b52f08442984ec8d16edb9fab69d05fc09f032a5dad7d9a1a77faa1ce7428120aea5732e00ac78a23a3e2af7c4ee11c447ea007c",
          "sha256": "55d3126104c1c6fc56d677c43ebbef80da4be7d60ab2051710a1ba0943abc2fa",
          "sha1": "339f15b5e6ba802dcf2e845a2a9cabbc6e09314e",
          "md5": "da723f406621330f49f220d6cb1187da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "2764266f0e1a05a2bfea3b54b52f08442984ec8d16edb9fab69d05fc09f032a5dad7d9a1a77faa1ce7428120aea5732e00ac78a23a3e2af7c4ee11c447ea007c",
          "sha256": "55d3126104c1c6fc56d677c43ebbef80da4be7d60ab2051710a1ba0943abc2fa",
          "sha1": "339f15b5e6ba802dcf2e845a2a9cabbc6e09314e",
          "md5": "da723f406621330f49f220d6cb1187da"
        }
      ]
    }
  ]
}
