{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.22.jar",
          "url": "injector-plugin-2.0.22.jar",
          "size": 135611,
          "sha512": "daa3ad38cbc7d913766d90ef37da6c1154ec05456fe6a0a2c104bb48d23b1949d3bfe23aa3aa965c2ff99a8fbeb79324334dad4d06463846b632b089379e527b",
          "sha256": "7528cc502e3e5ff018c01ff3d1017411123c180be16e4a1622b2fabb6b62e6b4",
          "sha1": "2b4cf43fab22bdada8510f9a61a44b81972f5a13",
          "md5": "e9af7db1ad9b4e4add3c2cda3978ac2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.22.jar",
          "url": "injector-plugin-2.0.22.jar",
          "size": 135611,
          "sha512": "daa3ad38cbc7d913766d90ef37da6c1154ec05456fe6a0a2c104bb48d23b1949d3bfe23aa3aa965c2ff99a8fbeb79324334dad4d06463846b632b089379e527b",
          "sha256": "7528cc502e3e5ff018c01ff3d1017411123c180be16e4a1622b2fabb6b62e6b4",
          "sha1": "2b4cf43fab22bdada8510f9a61a44b81972f5a13",
          "md5": "e9af7db1ad9b4e4add3c2cda3978ac2d"
        }
      ]
    }
  ]
}
