{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.12.jar",
          "url": "injector-plugin-2.0.12.jar",
          "size": 127744,
          "sha512": "317098cd02da79ae76368612475f2efe8d498c9a4d44a5b9fb9ac25fe929fadb16cbaf656b96538ce51987a13677bb67b56c5b1dd5b096af462d47664bc85a07",
          "sha256": "ca24f040075344eb639be2f1808440dc8d6cb807a358c0235fcf7c11d0a257d7",
          "sha1": "6aed00f4da7a2a3d4e84e750acf0ff290df5517e",
          "md5": "54b7b00da8c4962c8cd1b234277d6b32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.12.jar",
          "url": "injector-plugin-2.0.12.jar",
          "size": 127744,
          "sha512": "317098cd02da79ae76368612475f2efe8d498c9a4d44a5b9fb9ac25fe929fadb16cbaf656b96538ce51987a13677bb67b56c5b1dd5b096af462d47664bc85a07",
          "sha256": "ca24f040075344eb639be2f1808440dc8d6cb807a358c0235fcf7c11d0a257d7",
          "sha1": "6aed00f4da7a2a3d4e84e750acf0ff290df5517e",
          "md5": "54b7b00da8c4962c8cd1b234277d6b32"
        }
      ]
    }
  ]
}
