{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "script-assembler-plugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.2.jar",
          "url": "script-assembler-plugin-1.0.2.jar",
          "size": 7060,
          "sha512": "235f79df2585b0b714d5312c41ba51391ad83e5a1ab6d4401bf6c1df2e7881b43d5b51cf7e07a9d395219aed7a173c3917a3582a50204527745cac7a547a35b2",
          "sha256": "f81e6b7dbad8b1ae8be9e79c738312ecdb283b5086a1a6e68b5fb90f3dff11b7",
          "sha1": "8f54c16141ba8ac5d3793a90420e203f1c3c7f6d",
          "md5": "0498d73ef8af2699825c83c3e78f89da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "net.runelite",
          "module": "cache",
          "version": {
            "requires": "1.10.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.2.jar",
          "url": "script-assembler-plugin-1.0.2.jar",
          "size": 7060,
          "sha512": "235f79df2585b0b714d5312c41ba51391ad83e5a1ab6d4401bf6c1df2e7881b43d5b51cf7e07a9d395219aed7a173c3917a3582a50204527745cac7a547a35b2",
          "sha256": "f81e6b7dbad8b1ae8be9e79c738312ecdb283b5086a1a6e68b5fb90f3dff11b7",
          "sha1": "8f54c16141ba8ac5d3793a90420e203f1c3c7f6d",
          "md5": "0498d73ef8af2699825c83c3e78f89da"
        }
      ]
    }
  ]
}
