{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.26.jar",
          "url": "injector-plugin-2.0.26.jar",
          "size": 135986,
          "sha512": "f4f45c00cfaef71dec32f29f43dce8658d6e745676c300343087742c1b5ba2e099ce4918b9c98f93aaeea564b01f2fa2cd63625a9cea24f43edf804186a938fe",
          "sha256": "3bea6d2c26a696a3b7d90e4f12bde1eec28c89ddf3f82630cb6e0916d7ef533c",
          "sha1": "0a19cc6ddd152684b0feeffe32f0e2fc9c9376e1",
          "md5": "d299bb9d8e2493a57d23eadb70dda418"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.26.jar",
          "url": "injector-plugin-2.0.26.jar",
          "size": 135986,
          "sha512": "f4f45c00cfaef71dec32f29f43dce8658d6e745676c300343087742c1b5ba2e099ce4918b9c98f93aaeea564b01f2fa2cd63625a9cea24f43edf804186a938fe",
          "sha256": "3bea6d2c26a696a3b7d90e4f12bde1eec28c89ddf3f82630cb6e0916d7ef533c",
          "sha1": "0a19cc6ddd152684b0feeffe32f0e2fc9c9376e1",
          "md5": "d299bb9d8e2493a57d23eadb70dda418"
        }
      ]
    }
  ]
}
