{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.6.jar",
          "url": "injector-plugin-2.0.6.jar",
          "size": 123356,
          "sha512": "cac62878793247c553c0cf39e90bd7cefef201f07d92b1e594e74fa2128b011858aeabfaabcc90d8da759ee60d28b2699282a3d09924bf584b8d00619422bd17",
          "sha256": "fe893a4bd9493d65d0ed79640a63c44ba6ab1bd2dd22372e9048fe5d6f8765fa",
          "sha1": "720377bb77c83cffbe343437308ba7737eca2cf9",
          "md5": "83fa1785bfdb27dfe819ea7ab181f12c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.6.jar",
          "url": "injector-plugin-2.0.6.jar",
          "size": 123356,
          "sha512": "cac62878793247c553c0cf39e90bd7cefef201f07d92b1e594e74fa2128b011858aeabfaabcc90d8da759ee60d28b2699282a3d09924bf584b8d00619422bd17",
          "sha256": "fe893a4bd9493d65d0ed79640a63c44ba6ab1bd2dd22372e9048fe5d6f8765fa",
          "sha1": "720377bb77c83cffbe343437308ba7737eca2cf9",
          "md5": "83fa1785bfdb27dfe819ea7ab181f12c"
        }
      ]
    }
  ]
}
