{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.6.jar",
          "url": "injector-plugin-2.0.6.jar",
          "size": 127520,
          "sha512": "933645abb5d4fdbb7d14229ae41d32abfeb2f30aab4aaefc6a1374a5d2f0618f5b6557b6cb933f5c5cedb02abc89fea25c2b001289550287275cc1be4ff6e794",
          "sha256": "fdde4ac83143d60c159b94a6d7a5a605a515b2f7c63356fc73f2925e34d34fa0",
          "sha1": "01bf7e9cea6be92dde3e949d3f6eb076da4e8d91",
          "md5": "f13de5418578ab904a792c0b1a63e913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.6.jar",
          "url": "injector-plugin-2.0.6.jar",
          "size": 127520,
          "sha512": "933645abb5d4fdbb7d14229ae41d32abfeb2f30aab4aaefc6a1374a5d2f0618f5b6557b6cb933f5c5cedb02abc89fea25c2b001289550287275cc1be4ff6e794",
          "sha256": "fdde4ac83143d60c159b94a6d7a5a605a515b2f7c63356fc73f2925e34d34fa0",
          "sha1": "01bf7e9cea6be92dde3e949d3f6eb076da4e8d91",
          "md5": "f13de5418578ab904a792c0b1a63e913"
        }
      ]
    }
  ]
}
