{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.23.jar",
          "url": "injector-plugin-2.0.23.jar",
          "size": 133044,
          "sha512": "bafe8ab09814e41fd0f41b893b9b2d6f1d9ffec369bf51e8a430b189b6e1f305e81290af5c9a0599db08132d98ece021ae85d8c16850593d66bb4823441bbb36",
          "sha256": "9f74fd1deec67cf79e7fc993b6436289dc24abbff6ff0e36b91848563288962c",
          "sha1": "aaf0f38029cd55b6cacdbe1b237065c6d7e057df",
          "md5": "dd2ed8e0e2af4f93035b37441b7daa02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.23.jar",
          "url": "injector-plugin-2.0.23.jar",
          "size": 133044,
          "sha512": "bafe8ab09814e41fd0f41b893b9b2d6f1d9ffec369bf51e8a430b189b6e1f305e81290af5c9a0599db08132d98ece021ae85d8c16850593d66bb4823441bbb36",
          "sha256": "9f74fd1deec67cf79e7fc993b6436289dc24abbff6ff0e36b91848563288962c",
          "sha1": "aaf0f38029cd55b6cacdbe1b237065c6d7e057df",
          "md5": "dd2ed8e0e2af4f93035b37441b7daa02"
        }
      ]
    }
  ]
}
