{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "script-assembler-plugin",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.4.jar",
          "url": "script-assembler-plugin-1.0.4.jar",
          "size": 8723,
          "sha512": "cc60ea31e77d3df7e1aa198376571b45caec300b49f5de7ed79998577d509a2f936a2de4dab5faf19b5aabf8666746855c9d064f58c055d13d75931b99ca2f52",
          "sha256": "bde16f5972b33304648ac4ad2dda903faff667292d594d810a369cf6beb1e7f0",
          "sha1": "f13bb7d7fa24c55782fb49a036bf840ad64be6e8",
          "md5": "a726a596b053be8900151a34b242dea2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "net.runelite",
          "module": "cache",
          "version": {
            "requires": "1.11.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.4.jar",
          "url": "script-assembler-plugin-1.0.4.jar",
          "size": 8723,
          "sha512": "cc60ea31e77d3df7e1aa198376571b45caec300b49f5de7ed79998577d509a2f936a2de4dab5faf19b5aabf8666746855c9d064f58c055d13d75931b99ca2f52",
          "sha256": "bde16f5972b33304648ac4ad2dda903faff667292d594d810a369cf6beb1e7f0",
          "sha1": "f13bb7d7fa24c55782fb49a036bf840ad64be6e8",
          "md5": "a726a596b053be8900151a34b242dea2"
        }
      ]
    }
  ]
}
