{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.10.jar",
          "url": "injector-plugin-2.0.10.jar",
          "size": 127519,
          "sha512": "de6eb0a09e6b495027985280147569af6df2df44297de8daa85c3d192b64d99ae9b208ab65cd8abc8b607311ec219ac00489a8b4f32f93fec59015fb864e3b06",
          "sha256": "3dc7c2b47d4e43117ef9fbccb1dcc5171b9817529f27b594ed65de079f501ab1",
          "sha1": "e8460a4c9f337909ee332d7a57b69e333127173e",
          "md5": "59f053099a6fc82fe7b11cd4681b6102"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.10.jar",
          "url": "injector-plugin-2.0.10.jar",
          "size": 127519,
          "sha512": "de6eb0a09e6b495027985280147569af6df2df44297de8daa85c3d192b64d99ae9b208ab65cd8abc8b607311ec219ac00489a8b4f32f93fec59015fb864e3b06",
          "sha256": "3dc7c2b47d4e43117ef9fbccb1dcc5171b9817529f27b594ed65de079f501ab1",
          "sha1": "e8460a4c9f337909ee332d7a57b69e333127173e",
          "md5": "59f053099a6fc82fe7b11cd4681b6102"
        }
      ]
    }
  ]
}
