{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.15.jar",
          "url": "injector-plugin-2.0.15.jar",
          "size": 128106,
          "sha512": "0cd13bea2b62868e8279c2c8e3fabdbd0384602bb24a0fc2052468a62ba38aeb689784b57426bacd5b002d3f08ce190d8f133a7ddf5826e5718c99cb831e2f8e",
          "sha256": "10d30b8d9e81a88c891f828c00c1c41245ec40d4d1724a19076341ada22cf11a",
          "sha1": "b22e7d1c03157d4d7f2ec2cd412019490415ecbe",
          "md5": "7e777b625aca1e50b402ce7b89cb0650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.15.jar",
          "url": "injector-plugin-2.0.15.jar",
          "size": 128106,
          "sha512": "0cd13bea2b62868e8279c2c8e3fabdbd0384602bb24a0fc2052468a62ba38aeb689784b57426bacd5b002d3f08ce190d8f133a7ddf5826e5718c99cb831e2f8e",
          "sha256": "10d30b8d9e81a88c891f828c00c1c41245ec40d4d1724a19076341ada22cf11a",
          "sha1": "b22e7d1c03157d4d7f2ec2cd412019490415ecbe",
          "md5": "7e777b625aca1e50b402ce7b89cb0650"
        }
      ]
    }
  ]
}
