{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "5a1c8392c8e802d990a1c07e1f22ded3ba19cff50813393cbd4c8b1f088596c092d01bf3bd1bcc28198462f85607da4606ac14d5aa610d317d6b4b835618de2f",
          "sha256": "6f9563b4f2b74c5f9287450dffb13236fb6500281f425baca0d2d4c2d3dd20e7",
          "sha1": "332e843cac033cc1e9ba84f0adb1ba3c1e360e04",
          "md5": "138cfb659b01072a90944d0662e2a66d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "5a1c8392c8e802d990a1c07e1f22ded3ba19cff50813393cbd4c8b1f088596c092d01bf3bd1bcc28198462f85607da4606ac14d5aa610d317d6b4b835618de2f",
          "sha256": "6f9563b4f2b74c5f9287450dffb13236fb6500281f425baca0d2d4c2d3dd20e7",
          "sha1": "332e843cac033cc1e9ba84f0adb1ba3c1e360e04",
          "md5": "138cfb659b01072a90944d0662e2a66d"
        }
      ]
    }
  ]
}
