{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "8fcddb3a2b208d73d57f2c640e9249418e9ebf37d6e9229d1e9595c14e0edff32ad2f3935de39fe39d269d0fa9f7aeed8091daae0f2ca6feec2bc9bdb3f8a2f1",
          "sha256": "9c3066f81c9698e46a35ed78085549bd2d65898b12fd135bfa3ba7c2ec71079d",
          "sha1": "a2fe12a0d7f763af898a21da575f1d8c9e2faee1",
          "md5": "51c801a8c937b3f6bce143be233d1cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "8fcddb3a2b208d73d57f2c640e9249418e9ebf37d6e9229d1e9595c14e0edff32ad2f3935de39fe39d269d0fa9f7aeed8091daae0f2ca6feec2bc9bdb3f8a2f1",
          "sha256": "9c3066f81c9698e46a35ed78085549bd2d65898b12fd135bfa3ba7c2ec71079d",
          "sha1": "a2fe12a0d7f763af898a21da575f1d8c9e2faee1",
          "md5": "51c801a8c937b3f6bce143be233d1cef"
        }
      ]
    }
  ]
}
