{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "0949b104ef2fbb7a72840f3c768cefbc7a0fb28b56a35f3cebe3d329312ddb5ba539d505fe41704680cedf28dc43bb2e4d474d2fc9a7e92f272ac777224e256f",
          "sha256": "9e8bb0a883914f9f0933c9f6f3ad5fbcf6593f992cf4f95293b62998b81f4258",
          "sha1": "0a1ee08cadf4cb36b1b4c6199206735ca64fdb91",
          "md5": "704bea5701d8bb2e6678f71015e4e16c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "0949b104ef2fbb7a72840f3c768cefbc7a0fb28b56a35f3cebe3d329312ddb5ba539d505fe41704680cedf28dc43bb2e4d474d2fc9a7e92f272ac777224e256f",
          "sha256": "9e8bb0a883914f9f0933c9f6f3ad5fbcf6593f992cf4f95293b62998b81f4258",
          "sha1": "0a1ee08cadf4cb36b1b4c6199206735ca64fdb91",
          "md5": "704bea5701d8bb2e6678f71015e4e16c"
        }
      ]
    }
  ]
}
