{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.9.jar",
          "url": "injector-plugin-2.0.9.jar",
          "size": 128041,
          "sha512": "27a723d20dcf969f2f19b01f2ba8125183b92e13ab807062b842a5e9e37e55555c9f1283833c5b66add45f9470f88de0f8c4aee3427fcfcf69a4c36293ea0df7",
          "sha256": "230435daa1fd277e95515b396f5bc8bbd1558e9a01f2cfdcabb542db14ad6919",
          "sha1": "cc6ba7a60650a0629d36cb0833db1b62aab1b36f",
          "md5": "5716c5ba411ff57448081c9ee742f5d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.9.jar",
          "url": "injector-plugin-2.0.9.jar",
          "size": 128041,
          "sha512": "27a723d20dcf969f2f19b01f2ba8125183b92e13ab807062b842a5e9e37e55555c9f1283833c5b66add45f9470f88de0f8c4aee3427fcfcf69a4c36293ea0df7",
          "sha256": "230435daa1fd277e95515b396f5bc8bbd1558e9a01f2cfdcabb542db14ad6919",
          "sha1": "cc6ba7a60650a0629d36cb0833db1b62aab1b36f",
          "md5": "5716c5ba411ff57448081c9ee742f5d3"
        }
      ]
    }
  ]
}
