{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.20.jar",
          "url": "injector-plugin-2.0.20.jar",
          "size": 132927,
          "sha512": "ca3a289592498ab301267497f4ca85ad953dc97c0db0110f4beeb66019622cfc8314673ba043ff559ccbbe49037ff9b36ed319d8e593ed3b1521b9c4ab1c8e84",
          "sha256": "0d0526bcf8029e7ca3d777ee38126b5e4a87684d0d836e4ceca5324a56e9775d",
          "sha1": "aa7d188580912934bbc5ed5d80488858ead7c187",
          "md5": "db9d26b9325b8474ce46b53e701e2c55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.20.jar",
          "url": "injector-plugin-2.0.20.jar",
          "size": 132927,
          "sha512": "ca3a289592498ab301267497f4ca85ad953dc97c0db0110f4beeb66019622cfc8314673ba043ff559ccbbe49037ff9b36ed319d8e593ed3b1521b9c4ab1c8e84",
          "sha256": "0d0526bcf8029e7ca3d777ee38126b5e4a87684d0d836e4ceca5324a56e9775d",
          "sha1": "aa7d188580912934bbc5ed5d80488858ead7c187",
          "md5": "db9d26b9325b8474ce46b53e701e2c55"
        }
      ]
    }
  ]
}
