{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.13.jar",
          "url": "injector-plugin-2.0.13.jar",
          "size": 130007,
          "sha512": "3164f3b1e3920b09cc948b62993998fd5d0ef1eb5fbf892df15d753aae19aa924bc362404587b4e17de342cec1d04ec263db3796b58fbc7e5af932c1923cb342",
          "sha256": "9dd4b7ec4dac30be2e77bbfeb05a3af57136a5ef2061494b8a324233ee1b34a2",
          "sha1": "61845c668998ef3763eed830e1b9c8bd45e6ef23",
          "md5": "38eb67e1aae4ae6dddd7515617f752dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.13.jar",
          "url": "injector-plugin-2.0.13.jar",
          "size": 130007,
          "sha512": "3164f3b1e3920b09cc948b62993998fd5d0ef1eb5fbf892df15d753aae19aa924bc362404587b4e17de342cec1d04ec263db3796b58fbc7e5af932c1923cb342",
          "sha256": "9dd4b7ec4dac30be2e77bbfeb05a3af57136a5ef2061494b8a324233ee1b34a2",
          "sha1": "61845c668998ef3763eed830e1b9c8bd45e6ef23",
          "md5": "38eb67e1aae4ae6dddd7515617f752dc"
        }
      ]
    }
  ]
}
