{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.13.jar",
          "url": "injector-plugin-2.0.13.jar",
          "size": 127718,
          "sha512": "b10f0c5fd66006bb5c79d4e7dd6985c067fa2d94c9c4d08d32f45607f59acb6c6e49216aded4fb8e4e180ac551eadbc0c85c0e185514c2e8eb3d69d178d1a3bf",
          "sha256": "5d1aaecd00c7d14a4667739acceeaa91dffd8d995e91d93fd6d859199c535489",
          "sha1": "8c65f96376e5a71a70d3497e25ad46a7c2bbc161",
          "md5": "cce7655304c1e4bfe47921fc6104b846"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.13.jar",
          "url": "injector-plugin-2.0.13.jar",
          "size": 127718,
          "sha512": "b10f0c5fd66006bb5c79d4e7dd6985c067fa2d94c9c4d08d32f45607f59acb6c6e49216aded4fb8e4e180ac551eadbc0c85c0e185514c2e8eb3d69d178d1a3bf",
          "sha256": "5d1aaecd00c7d14a4667739acceeaa91dffd8d995e91d93fd6d859199c535489",
          "sha1": "8c65f96376e5a71a70d3497e25ad46a7c2bbc161",
          "md5": "cce7655304c1e4bfe47921fc6104b846"
        }
      ]
    }
  ]
}
